//Arrays

// let marks = [85,97,44,37,76,60];

// let sum=0;

// for(let val of marks){

//     sum=sum + val;
// }

// let avg=sum/marks.length;

// console.log(avg);


//2 Array practice qns

// let item = [250,645,300,900,50];

// console.log("orignal price",item);

// for(let i=0; i<item.length; i++){

//   let  offerval = item[i]/10;

//     item[i]=item[i]-offerval;
// }

// console.log(item);

//splice 

//let arr=[10,20,30,40,50]

//practice

let comapnies=["Bloomberg","Microsoft","Uber","Google","IBM","Netflix"];

console.log(comapnies);

let newcompny=comapnies.shift();
console.log(comapnies);