//conditional statements

// let age=17;

// if(age>=18){

//     console.log("You Can Vote");
// }

// if(age<18){

//     console.log("You Cannot Vote");
// }

// let mode="dark";
// let color;

// if(mode == "dark"){

//     color= "black";
// }

// if(mode=="light"){

//     color = "white";
// }

// console.log(color);

// let num=5;

// if(num%2==0){

//     console.log("Even No");
// } else{

//     console.log("Odd No");s
// }


// let num = prompt("Enter a No:");

// if (num%5 ===0){

//     console.log(num ,"is the multiple of 5");
// }
// else{
//     console.log(num, "is not multiple of 5");
// }

// let marks = prompt("Enter a marks");
// // let marks=75;
// // let grade ;
// if(marks>=80){

//     console.log("A");
// }
//  else if(marks<=79 && marks>=70){

//     console.log("B");
// }
//  else if(marks<=69 && marks>=60){

//     console.log("c");

//  }
//    else if(marks<=59 && marks>=50){

//     console.log("D");
//    }

//    else if(marks<=49 && marks>=0){

//     console.log("F");
//    }

   //for loop


//    for(let count=1;count<=5;count++) {

//     console.log("Apna College");
//    }

   //while loop

//    let i=1;

//    while(i<=5){

//       console.log(i);
//       i++

//    }


//for of for loop

// let str="Alpesh";
// let size=0;

// for(let val of str){

//     console.log("val=",val);
//     size++;
// }

// console.log("string size=",size);

//print even no

// for(let i=0;i<=100;i++){

//     if(i%2==0){
//     console.log(i);
//     }
// }

//game example

// let gamenum=30;

// let usernum= prompt("Guess the game no");

// while(usernum != gamenum){

//     usernum=prompt("wrong gameno choose again");
// }

// console.log("congrats yoeu Entered");

//Strings

//Template literals

// let specialString= `this is a template literal ${1+2+3+4}`;
//  console.log(specialString);

//Upper/Lower case

// let str="alpesh";

// let newstr=str.toUpperCase();
// console.log(newstr);

//practice string

let username= prompt("enter full name:");

// let str=str.length();

console.log("@"+username+username.length);